language: cpp
dist: trusty
script: make
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libpulse-dev
      env:
        - COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - llvm-3.9-dev
            - libstdc++-6-dev
            - libpulse-dev
      env:
        - COMPILER=clang++-3.9
env:
  global:
   - CXXFLAGS="$CXXFLAGS${CXXFLAGS:+ }-Werror"
before_install:
  - export CC="$COMPILER"
  - export CXX="$COMPILER"
  - ${CXX} --version
